from __future__ import annotations

import argparse
import json
from pathlib import Path

from ml.src.data.split_manager import SplitConfig
from ml.src.models.train_daily_best_hour import train_daily_best_hour_model
from ml.src.models.train_daily_clothing import train_daily_clothing_models
from ml.src.models.train_daily_suitability import train_daily_suitability_model
from ml.src.models.train_daily_umbrella import train_daily_umbrella_model
from ml.src.utils.paths import PROJECT_ROOT


def _write_validation_summary(results: dict, output_path: Path) -> None:
    lines = [
        "# Daily Validation Metrics",
        "",
        "Generated by `python -m ml.src.models.train_daily_pipeline`.",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Daily Umbrella F1 (val) | {results['umbrella']['f1']:.4f} |",
        f"| Best Outdoor Hour Accuracy (val) | {results['best_hour']['accuracy']:.4f} |",
        f"| Clothing Morning Accuracy (val) | {results['clothing']['morning']['accuracy']:.4f} |",
        f"| Clothing Afternoon Accuracy (val) | {results['clothing']['afternoon']['accuracy']:.4f} |",
        f"| Clothing Evening Accuracy (val) | {results['clothing']['evening']['accuracy']:.4f} |",
        f"| Avg Outdoor Suitability MAE (val) | {results['suitability']['mae']:.4f} |",
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def run_daily_training(
    force_rebuild_split: bool = False,
    split_config: SplitConfig | None = None,
    write_report: bool = True,
    report_path: Path | None = None,
) -> dict:
    umbrella = train_daily_umbrella_model(
        force_rebuild_split=force_rebuild_split,
        split_config=split_config,
    )
    best_hour = train_daily_best_hour_model(
        force_rebuild_split=False,
        split_config=split_config,
    )
    clothing = train_daily_clothing_models(
        force_rebuild_split=False,
        split_config=split_config,
    )
    suitability = train_daily_suitability_model(
        force_rebuild_split=False,
        split_config=split_config,
    )

    results = {
        "umbrella": umbrella["validation_metrics"],
        "best_hour": best_hour["validation_metrics"],
        "clothing": {
            "morning": clothing["morning"]["validation_metrics"],
            "afternoon": clothing["afternoon"]["validation_metrics"],
            "evening": clothing["evening"]["validation_metrics"],
        },
        "suitability": suitability["validation_metrics"],
    }

    if write_report:
        target_path = report_path or (PROJECT_ROOT / "docs" / "metrics_daily_validation.md")
        _write_validation_summary(results=results, output_path=target_path)
    return results


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train daily summary models.")
    parser.add_argument(
        "--strategy",
        choices=["chronological_by_date_windows", "monthly_chronological_ratio"],
        default="monthly_chronological_ratio",
    )
    parser.add_argument("--val-days", type=int, default=10)
    parser.add_argument("--test-days", type=int, default=10)
    parser.add_argument("--monthly-train-ratio", type=float, default=0.70)
    parser.add_argument("--monthly-val-ratio", type=float, default=0.15)
    parser.add_argument("--monthly-test-ratio", type=float, default=0.15)
    parser.add_argument("--force-rebuild-split", action="store_true")
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    config = SplitConfig(
        strategy=args.strategy,
        val_days=args.val_days,
        test_days=args.test_days,
        monthly_train_ratio=args.monthly_train_ratio,
        monthly_val_ratio=args.monthly_val_ratio,
        monthly_test_ratio=args.monthly_test_ratio,
    )
    results = run_daily_training(
        force_rebuild_split=args.force_rebuild_split,
        split_config=config,
        write_report=True,
    )
    print("Daily training pipeline complete.")
    print(json.dumps(results, indent=2))

