from __future__ import annotations

import argparse
import json
from pathlib import Path

from ml.src.data.split_manager import SplitConfig
from ml.src.models.train_activity_go_no import train_activity_go_no_model
from ml.src.models.train_activity_suitability import train_activity_suitability_model
from ml.src.utils.paths import PROJECT_ROOT


def _write_validation_summary(results: dict, output_path: Path) -> None:
    lines = [
        "# Activity Validation Metrics",
        "",
        "Generated by `python -m ml.src.models.train_activity_pipeline`.",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Activity Go/No-Go F1 (val) | {results['go_no']['f1']:.4f} |",
        f"| Activity Go/No-Go Accuracy (val) | {results['go_no']['accuracy']:.4f} |",
        f"| Activity Suitability MAE (val) | {results['suitability']['mae']:.4f} |",
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def run_activity_training(
    force_rebuild_split: bool = False,
    split_config: SplitConfig | None = None,
    write_report: bool = True,
    report_path: Path | None = None,
) -> dict:
    go_no = train_activity_go_no_model(
        force_rebuild_split=force_rebuild_split,
        split_config=split_config,
    )
    suitability = train_activity_suitability_model(
        force_rebuild_split=False,
        split_config=split_config,
    )
    results = {
        "go_no": go_no["validation_metrics"],
        "suitability": suitability["validation_metrics"],
    }
    if write_report:
        target_path = report_path or (PROJECT_ROOT / "docs" / "metrics_activity_validation.md")
        _write_validation_summary(results=results, output_path=target_path)
    return results


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train activity recommendation models.")
    parser.add_argument(
        "--strategy",
        choices=["chronological_by_date_windows", "monthly_chronological_ratio"],
        default="monthly_chronological_ratio",
    )
    parser.add_argument("--val-days", type=int, default=10)
    parser.add_argument("--test-days", type=int, default=10)
    parser.add_argument("--monthly-train-ratio", type=float, default=0.70)
    parser.add_argument("--monthly-val-ratio", type=float, default=0.15)
    parser.add_argument("--monthly-test-ratio", type=float, default=0.15)
    parser.add_argument("--force-rebuild-split", action="store_true")
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    config = SplitConfig(
        strategy=args.strategy,
        val_days=args.val_days,
        test_days=args.test_days,
        monthly_train_ratio=args.monthly_train_ratio,
        monthly_val_ratio=args.monthly_val_ratio,
        monthly_test_ratio=args.monthly_test_ratio,
    )
    results = run_activity_training(
        force_rebuild_split=args.force_rebuild_split,
        split_config=config,
        write_report=True,
    )
    print("Activity training pipeline complete.")
    print(json.dumps(results, indent=2))

